- package.json
- yarn.lock
This will remove dependency warnings when using package with Angular 4
> Update peer-dependencies to support Angular 4

- README.md
- package.json
- src/app/markdown-to-html/markdown-to-html.component.ts
- tsconfig.json
- yarn.lock
Added `marked` import back with [Rollup issue workaround](https://github.com/rollup/rollup/issues/670#issuecomment-284621537) to import namespace
> Fix marked import

- README.md
Hi @jfcere, I ran into this when upgrading my app to Angular v6, and I thought I would send a PR documenting the solution I used, in case it's helpful. If whitespace (including newlines) are stripped out from the template, it causes issues in the rendered Markdown (in my case, it put almost everything into the the content's first heading, due to the newlines being removed.)
I also wonder if the markdown directive could be updated to also take care of telling the Angular template compiler to preserve whitespace, but I haven't looked into it yet.
> Add note about potential whitespace issues in Angular v6, and possible solution

- README.md
- lib/src/markdown.component.ts
Implemented `load` output event property on `markdown.component` to emit when source is loaded.
> Added `load` output event property to `markdown.component`

- lib/src/markdown.pipe.spec.ts
- lib/src/markdown.pipe.ts
> Return empty string when value is null/undefined using MarkdownPipe

- lib/src/markdown.service.ts
This fix runtime error on IE11 submited on #170
> Fix #170 querySelectorAll#forEach does not exist on IE11

- lib/package.json
- lib/src/markdown.component.ts
- lib/src/markdown.service.ts
To solve my issue #181 of having LaTeX in ngx-markdown I propose to add katex, which allows to write $f(x) = e^x$ (at the beginning of a line) and replaced by the LaTeX equation.
To use katex, "useKatex" should be included like 
```
<markdown [data]="..." useKatex></markdown>
```
and to the angular.json file the katex css should be added like
```
...
"styles": [
...,
"node_modules/katex/dist/katex.css"
]
```
Katex is included by applying it in the compile() function after precompile and before using marked.
> Add katex to support LaTeX

- LICENSE
- README.md
- angular.json
- demo/src/app/app.module.ts
- lib/package.json
- lib/src/markdown.component.spec.ts
- lib/src/markdown.module.spec.ts
- lib/src/markdown.module.ts
- lib/src/markdown.pipe.spec.ts
- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
- lib/src/marked-options.ts
- lib/tsconfig.lib.json
- lib/tsconfig.lib.prod.json
- package.json
- yarn.lock
The following modifications has been done to `MarkdownModule` configuration:
- Removed `MarkedOptions.tables` option (now enabled with `gfm`)
- Removed `MarkedOptions.sanitize` and `sanitizer` options (deprecated by marked.js)
- Changed `MarkedOptions.smartLists` default value to `false` (to be inline with marked.js)
- Added `sanitize` option to specify `SecurityContext` when sanitizing (defaulted to `SecurityContext.HTML`)
> Update marked 8

- README.md
I believe this will make the docs more consistent and easier to understand.
> Add marked.js imports to angular.json examples

- .eslintrc.json
- lib/src/markdown.pipe.spec.ts
- lib/src/markdown.pipe.ts
Because `MarkdownPipe` uses the `MarkdownService` to parse markdown to HTML, and it is already being sanitized in the service, it is safe to use `bypassSecurityTrustHtml` in `MarkdownPipe` to avoid HTML being stripped by Angular default sanitization behavior when using `innerHTML`.
Fix #126
> Fix stripped HTML using pipe

- README.md
- demo/src/app/app.module.ts
- lib/package.json
- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
- package.json
- yarn.lock
Related marked issue: https://github.com/markedjs/marked/issues/2358
Discussion on @types/marked package: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58301
- JS file for marked changed from `node_modules/marked/lib/marked.js` to `node_modules/marked/marked.min.js` and should be changed accordingly in `angular.json` scripts section
Fix #352, #357
> Update marked 4

- README.md
- angular.json
- demo/src/app/plugins/plugins.component.html
- demo/src/app/plugins/plugins.component.ts
- demo/src/app/plugins/remote/mermaid-options.html
- demo/src/app/plugins/remote/mermaid.html
- demo/src/prism.ts
- demo/src/scss/prism-theme.scss
- lib/package.json
- lib/src/index.ts
- lib/src/markdown.component.spec.ts
- lib/src/markdown.component.ts
- lib/src/markdown.module.spec.ts
- lib/src/markdown.pipe.spec.ts
- lib/src/markdown.pipe.ts
- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
- lib/src/mermaid-options.ts
- package.json
- yarn.lock
⚠ Breaking changes
- `MarkdownService.compile` function has been renamed to `parse` and its parameters combined into the `parseOptions` object;
- `MarkdownService.render` function has been added to render elements once markdown has been parsed into HTML;
- `MarkdownService.renderKatex` function is now private and called within the `MarkdownService.render` function;
Fixes #370
> Add mermaid integration

- lib/src/clipboard-button.component.ts
- lib/src/markdown.component.ts
- lib/src/markdown.service.spec.ts
- package.json
- yarn.lock
- Fix backward compatibility for `rxjs` version `^6.5.3`
Fix #397, #398
> Fix backward compatibility for rxjs 6

- lib/package.json
- package.json
- yarn.lock
Update `emoji-toolkit` optional dependency to [v7.0.0](https://github.com/joypixels/emoji-toolkit/releases/tag/7.0.0) to support [Unicode 14](https://emojipedia.org/unicode-14.0/).
> Update Emoji-Toolkit to v7.0.0

- README.md
- lib/src/markdown.component.spec.ts
- lib/src/markdown.component.ts
- lib/src/markdown.pipe.spec.ts
- lib/src/markdown.pipe.ts
- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
- Add `disableSanitizer: boolean` option as an input property to `MarkdownComponent` and as a parameter to `MarkdownPipe`, allowing to bypass the DOM sanitizer
🥇 Thanks to [paviad](https://github.com/paviad) for his contribution to adding the `disableSanitizer` option.
Fix #428 | Replace #429
> Add option to disable sanitizer in both component and pipe

- .circleci/config.yml
- README.md
- lib/src/markdown.component.spec.ts
- lib/src/markdown.component.ts
- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
- Add `srcRelativeLink: boolean` input property to `MarkdownComponent` to support relative links for remotely loaded markdown (default is `false`)
🥇 Thanks to [datumgeek](https://github.com/datumgeek) for his contribution to adding the `srcRelativeLink` option.
Fix #227 | Replace #417, #228
> Add support for relative links when using src input property

- lib/src/markdown.component.ts
- Fix `data` and `src` input properties type to allow `null` value due to the return type of the `async` pipe output
Fix #433
> Handle null value for data and src input properties

- lib/package.json
`zone.js` v0.13.0 was recently released, which should be marked as supported by this library. It was a bug fix only release, so it shouldn't affect this project in any way, see their [changelog](https://github.com/angular/angular/blob/main/packages/zone.js/CHANGELOG.md#013-2023-02-28).
> feat: allow zone.js v0.13.x

- demo/src/app/app.component.html
- demo/src/app/app.component.scss
- demo/src/app/app.component.theme.scss
- demo/src/app/app.component.ts
- demo/src/app/app.module.ts
- demo/src/app/bindings/bindings.module.ts
- demo/src/app/plugins/plugins.component.ts
- demo/src/app/plugins/plugins.module.ts
- demo/src/app/rerender/rerender.module.ts
- demo/src/app/shared/clipboard-button/clipboard-button.component.scss
- demo/src/app/shared/clipboard-button/clipboard-button.component.ts
- demo/src/app/shared/clipboard-button/clipboard-button.module.ts
- demo/src/app/shared/scrollspy-nav-layout/scrollspy-nav-layout.component.scss
- demo/src/app/shared/scrollspy-nav-layout/scrollspy-nav-layout.module.ts
- demo/src/scss/_typography.scss
- demo/src/scss/material-theme.scss
- demo/src/styles.scss
Remove @angular/material legacy modules and complete migration to MDC components
> Remove @angular/material legacy modules in demo

- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
Fix mermaid rendering by targeting nodes that are inside the component/directive element instead or relating on the query selector that goes through the whole document.
Related #475
> Render only mermaid elements within the component/directive

- README.md
- lib/package.json
- package.json
- yarn.lock
- Update `emoji-toolkit` to 8.0.0 to support unicode 15.0
> Update emoji-toolkit lib to 8.0.0

- lib/src/markdown.service.spec.ts
- lib/src/markdown.service.ts
- Fix custom renderer gets overridden when using MarkdownPipe
Fix #456
> Fix custom renderer gets overridden when using MarkdownPipe

- lib/src/provide-markdown.ts
It looks like the fix is as simple as adjusting the definition of `provideMarkdown` to not have the call to `makeEnvironmentProviders`.
It looks like this method is meant to enforce a rule that the provider only be usable in root, but that's not required. By relaxing this requirement I was able to move the `provideMarkdown` call into the component itself instead of the `app.config.ts` file.
To prove my theory,
As part of my testing of the demo app, this allowed the `marked` dep to not be part of the initial page bundle, effectively allowing for ~90 KB reduction from `marked`, `github-slugger`, and some `rxjs` dependences used in the app demo.
Before:
After:
**NOTE**: for simplicity, this PR is targeted to only update the `provideMarkdown` method and does not change any tests or code in …
> Relax provideMarkdown method usage to not require environment provider

- lib/src/markdown.component.ts
Add `buttonComponent` and `buttonTemplate` attributes from template conditionally (only when defined), to not overwrite globally defined values.
> Fix globally imported CLIPBOARD_OPTIONS (#529)
