README.md
src/app/markdown/markdown.component.spec.ts
src/app/markdown/markdown.component.ts

Add error output property to MarkdownComponent

---

src/app/markdown/markdown.service.spec.ts
src/app/markdown/markdown.service.ts

See PR #50
> `window` is not available when using server side rendering (universal).

Fix Prism declaration for server-side rendering

---

lib/public_api.ts

Fix lib export

---

demo/src/app/app.component.scss
lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts
lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts

Add decodeHTML for interpolation

---

lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts

Fix indent detection

---

lib/package.json
yarn.lock

Update @types/marked and marked dependencies

---

lib/src/markdown.service.ts

Validate platform for syntax highlight

---

lib/package.json
yarn.lock

- Update `marked` to v0.6.0
- Update `@types/marked` to v0.6.0

Update marked and @types/marked dependencies

---

lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts

Make MarkdownService.highlight parameter `element` optional

---

demo/src/app/app.component.html
demo/src/app/app.component.ts
demo/src/app/remote/markdown-pipe.html
lib/package.json
lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts
package.json

Fix plugins using Data input property

---

demo/src/app/markdown/code-and-synthax-highlighting.md
lib/package.json
lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts
yarn.lock

Fix code block highlight with no language

---

lib/package.json
lib/src/markdown.module.spec.ts
lib/src/markdown.module.ts
package.json

Fix Ivy compilation

---

lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts

Fix empty string with data binding

---

angular.json
demo/src/app/app.component.html
demo/src/app/app.component.scss
demo/src/app/app.component.ts
lib/src/markdown.service.ts

Fix Katex parsed HTML

---

README.md
lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts

Emit Ready output property when done parsing

---

README.md
angular.json
demo/src/app/app.component.html
demo/src/app/app.component.scss
demo/src/app/app.component.ts
demo/src/app/remote/emoji.html
lib/package.json
lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts
lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts
package.json
yarn.lock

Add emoji plugin

---

README.md
demo/src/app/app.component.html
lib/src/markdown.component.ts
tsconfig.json

Fix type checking when using `"strictTemplates": true`

---

README.md
demo/browserslist
demo/src/app/plugins/plugins.component.html
demo/src/prism.ts
demo/src/scss/prism-theme.scss

Remove lookbehind regex in demo

---

lib/package.json
package.json
yarn.lock

- Update Emoji-Toolkit version to 6.0.0
- Update Katex to version 0.12.0

Update Emoji-Toolkit and Katex

---

lib/package.json
yarn.lock

Update Emoji-Toolkit dependency

---

lib/package.json
lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts
package.json

Fix error thrown when using Katex or Emoji with SSR

---

lib/package.json
package.json
yarn.lock

Update marked 2.0.0

---

lib/package.json

Update zone.js peer dependency version

---

lib/src/language.pipe.spec.ts
lib/src/language.pipe.ts

Handle null/undefined parameters in LanguagePipe

---

lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts

Fix LineHighlight plugin horizontal scroll

---

lib/package.json

Adjust rxjs peer dependency to match @angular/core

---

lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts

- Fix language resolution when using `src` input property with and URL that has no file extension
Replace #287

Fix extension resolution when URL has no file extension

---

lib/src/markdown.pipe.ts
lib/src/markdown.service.ts

feat: add option to disable sanitizer in pipe

---

lib/src/markdown.component.ts
lib/src/markdown.service.ts

Minimal changes to support relative paths.  existing users should be unaffected as the default is false.

add enableBasePath Input to support relative paths

---

lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts

- Fix SSR markdown parsing
Fix #409

Fix marked SSR rendering

---

lib/package.json
lib/src/markdown.service.ts
lib/src/mermaid-options.ts
package.json
yarn.lock

I've added RunOptions in MermaidAPI.Config accommodate mermaid Runoptions in order to execute run() as init() method is deprecated in 10.2.4

Update mermaid.js lib to 10.2.4

---

.circleci/config.yml
.eslintrc.json
README.md
demo/src/app/plugins/plugins.component.html
demo/src/app/plugins/plugins.component.ts
demo/src/app/syntax-highlight/syntax-highlight.component.ts
lib/package.json
lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts
lib/src/mermaid-options.ts
package.json
yarn.lock

- Update `mermaid.js` to 10.6.0
🥇 Thanks to @sarfudheen for his contribution to update `mermaid.js` library.
Replace #463

Update mermaid.js lib to 10.6.0

---

.circleci/config.yml
LICENSE

Update CircleCI browser-tools orb version

Fix CircleCI chrome installation

---

.vscode/settings.json
README.md
lib/package.json
lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts
package.json
yarn.lock

- Add support for `marked` >= 9.0.0 < 13.0.0
Fix #495

Add marked 12 support

---

lib/src/markdown.service.spec.ts
lib/src/markdown.service.ts

- Fix clipboard button when used with `katex` directive
Fixes #492

Fix clipboard button when used with katex directive

---

lib/src/markdown.service.ts

- Fix clipboard uses with Prism coy theme
Fixes #411

Fix clipboard uses with Prism coy theme

---

demo/src/app/plugins/plugins.component.ts
lib/src/markdown.component.spec.ts
lib/src/markdown.component.ts

- Fix globally imported `CLIPBOARD_OPTIONS`
🥇 Thanks to @klofi for his contribution
Fix #529 | Replace #537

Fix globally imported CLIPBOARD_OPTIONS

---

README.md
lib/package.json
package.json
yarn.lock

- Add support for `emoji-toolkit` version 9.0.0, Unicode 15.1

Add support for emoji-toolkit 9.0.0

---

README.md
lib/package.json
package.json
yarn.lock

- Add support for mermaid version 11
Fix #535 | Replace #543

Add support for mermaid 11.0.0

---

README.md
demo/src/app/app.config.ts
lib/src/markdown.module.spec.ts
lib/src/markdown.module.ts
lib/src/marked-extensions.ts
lib/src/provide-markdown.ts

- Allow dependency injection when providing marked extensions
Fix #561

feat: Allow dependency injection for marked extensions

---

README.md
lib/package.json
package.json
yarn.lock

Fix vulnerability issue: https://github.com/advisories/GHSA-x7hr-w5r2-h6wg
Fix: https://github.com/jfcere/ngx-markdown/issues/575

fix: update prismjs to 1.30.0
